"""
prompts.py — Prompts enviados ao Gemini para extração de dados dos PDFs.
PROMPT_NORMAL: para matrículas (laudo normal).
PROMPT_ANTIGO: para laudos já preenchidos (laudo antigo).
"""
# PROMPTS
# ──────────────────────────────────────────────────────────────
PROMPT_NORMAL = (
    "Analise esta matrícula e retorne APENAS um JSON válido sem texto extra, sem markdown. "
    "Campos obrigatórios:\n"
    "- cri: nome do cartório em Title Case, sem nome do oficial\n"
    "- testada: medida do lado do imóvel que faz confrontação com a RUA ou LOGRADOURO PÚBLICO (frente do imóvel). "
    "Identifique nas confrontações qual lado confronta com rua, avenida, travessa, alameda ou logradouro e use APENAS essa medida. "
    "Formato: número exato + ' metros' (ex: '7,00 metros'). Se não houver confrontação com rua, retorne null\n"
    "- profundidade: medida do lado perpendicular à testada (lado do imóvel), número exato + ' metros' ou null se não constar\n"
    "- incra: se RURAL, código INCRA exato (ex: '950.114.354.341-4'); se URBANO, inscrição imobiliária municipal exata "
    "(ex: '03.01.00005.00003.1'). Procure por 'Inscrição Imobiliária', 'Insc. Imob.', 'Cadastro Municipal', 'Cód. INCRA', 'INCRA' ou similar. Retorne null se não encontrado\n"
    "- car: código CAR exato ou null\n"
    "- cidades_vizinhas: array com os 2 municípios mais populosos que fazem divisa direta com o município do imóvel — use seu conhecimento geográfico do Brasil para determinar, não deixe null\n"
    "- rodovias_acesso: OBRIGATÓRIO — retorne APENAS UMA rodovia, a principal de acesso ao imóvel (ex: 'BR-282'). "
    "Se houver várias no documento, escolha a mais relevante. "
    "Se não constar, use seu conhecimento geográfico para informar a rodovia federal ou estadual mais próxima — NUNCA retorne null\n"
    "- proprietarios: array de strings em Title Case, cada item com nome + CPF ou CNPJ se presente (ex: ['João da Silva - CPF 000.000.000-00'])\n"
    "- endereco: SOMENTE o logradouro, no formato 'Rua Nome', 'Estrada Nome' ou 'Rodovia Nome/Sigla' — sem número, sem complemento\n"
    "- numero: número do imóvel exato ou 'S/N' se não houver\n"
    "- bairro: nome do bairro ou null\n"
    "- complemento: APENAS uma das categorias a seguir se aplicável — 'Fazenda Nome', 'Linha Nome', 'Lote N', 'Loteamento Nome', 'Quadra N', 'Condomínio Nome' ou 'Edifício Nome'; null se nenhuma se aplicar\n"
    "- unidade: identificação exata da unidade autônoma como consta no documento, se houver (ex: 'Casa nº 01', 'Apartamento nº 302', 'Sala 05'). Retorne null se não houver unidade específica (terreno simples)\n"
    "- pavimento: número do pavimento da unidade autônoma como consta no documento (ex: '3', '10'). Retorne null se não houver\n"
    "- areas_privativas: se o documento descrever áreas da unidade autônoma (área privativa, área de uso comum, fração ideal, área total, etc.), retorne array de objetos com {tipo: string exato como consta no documento, valor: string numérica com vírgula decimal}. Ex: [{tipo:'área privativa',valor:'73,76'},{tipo:'área de uso comum',valor:'0,10'},{tipo:'área total',valor:'73,86'}]. Retorne null se não houver\n"
    "- tipo_imovel: 'RURAL' ou 'URBANO'\n"
    "- area_total: área total do imóvel. Se RURAL, SEMPRE converta para hectares (ha) independente da unidade original "
    "(ex: 10.512 m² → '1,0512 ha', 43.560 m² → '4,3560 ha'). Se URBANO, retorne em m² (ex: '600,00 m²')\n"
    "- cidade: nome do município\n"
    "- uf: sigla do estado (ex: 'SC')\n"
    "- averbacoes: liste SOMENTE construções, edificações ou demolições com AV. explícita no documento — este campo vai para a API\n"
    "- averbacoes_classificadas: CRÍTICO — leia TODAS as averbações do documento e classifique por tipo. Retorne objeto com estas chaves exatas: construcoes_demoliciones (lista de strings com cada AV. de construção, edificação ou demolição), areas_nao_edificaveis (lista de strings com cada AV. de área não edificável, faixa non aedificandi, servidão), ferrovias_gasodutos (lista de strings com cada AV. de ferrovia, gasoduto, oleoduto, duto ou faixa de servidão de passagem), desmembramentos (lista de strings com cada AV. de desmembramento ou divisão de área), remembramentos (lista de strings com cada AV. de remembramento ou unificação de área), reservas_legais (lista de strings com cada AV. de reserva legal, APP ou área de preservação). Se não houver nenhuma de um tipo, retorne lista vazia []. Copie o texto de cada averbação EXATAMENTE como consta no documento, incluindo número da AV. e data\n"
    "se nenhuma, retorne 'Não há averbações de construção ou demolição'\n"
    "- analise_juridica: CRÍTICO — analise TODAS as averbações, registros, ônus e restrições do documento. "
"Para cada ocorrência encontrada, retorne um objeto com: "
"id_av (número/identificador da averbação exatamente como consta no documento, ex: 'AV. 3', 'AV. 13.123', 'R.3'; se não houver identificador, use 'Averbação sem número identificado'), "
"tipo (categoria: 'Ônus e Gravames', 'Ações Judiciais e Litígios', 'Restrições Administrativas/Urbanísticas/Ambientais', 'Riscos Dominiais e Registrais', 'Direitos de Terceiros/Ocupação'), "
"subtipo (ex: 'Alienação fiduciária', 'Hipoteca', 'Penhora', 'APP', 'Embargo', 'Usufruto', 'Servidão', etc.), "
"descricao (descrição resumida do conteúdo), "
"credora (nome da instituição credora/beneficiária se houver, null se não houver), "
"cancelada (true se a averbação já foi expressamente cancelada/baixada no documento, false se vigente ou indefinido), "
"impacto ('Baixo', 'Médio' ou 'Alto'). "
"IMPORTANTE: inclua APENAS ocorrências que representem risco jurídico, restrição, ônus, limitação ao domínio, "
"redução de liquidez ou potencial impacto negativo na negociação. NÃO inclua averbações de construção, "
"demolição, desmembramento ou remembramento (essas já estão em averbacoes_classificadas). "
"NÃO inclua averbações já canceladas. "
"Se não houver nenhuma ocorrência relevante, retorne lista vazia [].\n"
    "- azimutes: CRÍTICO — procure no documento descrição de perímetro com azimutes e distâncias. Esse formato aparece como texto corrido, ex: 'A poligonal tem início no ponto P1, de coordenadas E:378961.094 e N:7015397.121, segue com o azimute de 175°08\'34\" e percorre 234,57m, até o ponto P2'. Extraia TODOS os trechos em ordem, do P1 até fechar o polígono. Para cada trecho retorne: {ponto_origem: 'P1', azimute: '175d08m34s', distancia_m: 234.57}. IMPORTANTE: converta o azimute para o formato grausXminutosYsegundosZ, ex: 175°08\'34\" → '175d08m34s'. O primeiro ponto DEVE ter coordenadas UTM (E e N) — extraia essas coordenadas também no campo coordenadas. Se não houver descrição por azimutes no documento, retorne null\n"
    "- coordenadas: CRÍTICO — procure coordenadas em TODO o documento, incluindo tabelas SIGEF/INCRA que podem se estender por VÁRIAS PÁGINAS. "
    "Formatos possíveis:\n"
    "(1) DECIMAL simples: '-29.184530, -51.180262' → formato:'DECIMAL', pontos:[{x:longitude,y:latitude}]\n"
    "(2) GMS em tabela SIGEF/INCRA: a tabela tem colunas Código, Longitude, Latitude, Altitude, etc. "
    "Longitude no formato '-51°14'02,673\"' e Latitude no formato '-28°02'24,036\"'  ou com vírgula como decimal. "
    "ATENÇÃO: a tabela pode ter 100+ linhas espalhadas por múltiplas páginas — leia TODAS as páginas e extraia ABSOLUTAMENTE TODOS os vértices sem exceção. "
    "Não pare de ler antes de chegar ao fim da tabela. Cada linha é um vértice e todos são necessários para fechar o polígono corretamente. "
    "Converter: grau = parte inteira, minuto = segundos parte do meio, segundo = parte decimal convertida. "
    "Hemisfério: longitude negativa = W (Oeste), latitude negativa = S (Sul). "
    "Use formato:'GMS', pontos:[{lat_g,lat_m,lat_s,lat_hem,lon_g,lon_m,lon_s,lon_hem}]\n"
    "(2) GMS em tabela SIGEF/INCRA: colunas Código, Longitude, Latitude, Altitude. "
    "Longitude ex: '-51°14\'02,673\"' — grau=51, minuto=14, segundo=02.673 (vírgula→ponto). "
    "Latitude ex: '-28°02\'24,036\"' — grau=28, minuto=02, segundo=24.036. "
    "(3) UTM com zona → formato:'UTM', pontos:[{x,y}]\n"
    "(4) Coordenadas UTM sem zona explícita — ex: E:378961.094 e N:7015397.121 em documento com azimutes: use formato:'UTM', zona_utm:22, hemisferio:'S', pontos:[{x:378961.094,y:7015397.121}]\n"
    "Se não houver coordenadas, retorne null. "
    "Objeto: {formato:'UTM'/'GMS'/'DECIMAL', zona_utm:int ou null, hemisferio:'S'/'N' ou null, "
    "pontos: UTM:[{x,y}] / GMS:[{lat_g,lat_m,lat_s,lat_hem,lon_g,lon_m,lon_s,lon_hem}] / DECIMAL:[{x:lon,y:lat}]}\n"
    "- vaga_garagem: true se houver qualquer menção a vaga de garagem, box ou garagem no documento (em averbações, descrição do imóvel, matrícula ou qualquer parte do texto); false se não houver nenhuma menção.\\n"
    "- vaga_garagem: true se houver qualquer menção a vaga de garagem, box ou garagem no documento; false se não houver nenhuma menção.\\n"
    "- matricula_cancelada: CRÍTICO — verifique se a PRÓPRIA matrícula analisada consta como cancelada, encerrada, "
    "extinta ou transferida para outra matrícula (ex: 'matrícula cancelada', 'encerrada por unificação', "
    "'encerrada por desmembramento', 'transferida para a matrícula nº X'). Retorne objeto "
    "{cancelada: true/false, motivo: string com o texto/trecho exato que indica o cancelamento, ou null se não houver}. "
    "Se não houver nenhuma indicação de cancelamento/encerramento, retorne {cancelada: false, motivo: null}\n"
    "- croqui_svg: Gere um croqui SVG desta matrícula, analisando rigorosamente as posições e o ponto de observação "
    "descritos para posicionar corretamente as divisas e confrontantes. Retorne o código SVG completo como string "
    "(começando com '<svg' e terminando com '</svg>'), com os lados identificados (frente/fundos/laterais) e os "
    "nomes dos confrontantes de cada lado, quando descritos no documento. É um esquema ilustrativo baseado na "
    "descrição textual, não uma medição precisa. Retorne null se não houver confrontações/posições suficientes no "
    "documento para desenhar algo minimamente confiável\n"
    "Retorne SOMENTE o JSON, sem explicações, sem markdown."
)

PROMPT_MULTIPLO = (
    "Você vai receber de 1 a 10 PDFs de matrículas de imóveis, cada um em um arquivo separado, "
    "na mesma ordem em que foram anexados a esta mensagem. "
    "CRÍTICO — REGRA OBRIGATÓRIA: o array 'matriculas' do JSON de resposta DEVE conter EXATAMENTE "
    "um objeto para CADA PDF recebido, na mesma ordem, NUNCA a menos. Se você não conseguir ler ou "
    "extrair algum campo de um dos PDFs, ainda assim inclua um objeto para ele com os campos que "
    "conseguir preencher e null nos demais — NUNCA omita um PDF inteiro da lista. Antes de responder, "
    "confira que a quantidade de objetos em 'matriculas' é IGUAL à quantidade de PDFs anexados a esta mensagem.\n"
    "Analise CADA PDF individualmente e retorne APENAS um JSON válido, sem texto extra, sem markdown, no formato:\n"
    "{\n"
    '  "matriculas": [ ... um objeto por PDF, na mesma ordem em que foram enviados ... ],\n'
    '  "analise_confrontantes": { "sao_confrontantes": true/false, "explicacao": "..." }\n'
    "}\n\n"
    "Cada objeto dentro de 'matriculas' deve ter os campos:\n"
    "- numero_matricula: número da matrícula exatamente como consta no documento (ex: '34.319')\n"
    "- cri: nome do cartório em Title Case, sem nome do oficial\n"
    "- testada: medida do lado do imóvel que faz confrontação com a RUA ou LOGRADOURO PÚBLICO (frente do imóvel). "
    "Identifique nas confrontações qual lado confronta com rua, avenida, travessa, alameda ou logradouro e use APENAS essa medida. "
    "Formato: número exato + ' metros' (ex: '7,00 metros'). Se não houver confrontação com rua, retorne null\n"
    "- profundidade: medida do lado perpendicular à testada (lado do imóvel), número exato + ' metros' ou null se não constar\n"
    "- incra: se RURAL, código INCRA exato (ex: '950.114.354.341-4'); se URBANO, inscrição imobiliária municipal exata "
    "(ex: '03.01.00005.00003.1'). Procure por 'Inscrição Imobiliária', 'Insc. Imob.', 'Cadastro Municipal', 'Cód. INCRA', 'INCRA' ou similar. Retorne null se não encontrado\n"
    "- car: código CAR exato ou null\n"
    "- cidades_vizinhas: array com os 2 municípios mais populosos que fazem divisa direta com o município do imóvel — use seu conhecimento geográfico do Brasil para determinar, não deixe null\n"
    "- rodovias_acesso: OBRIGATÓRIO — retorne APENAS UMA rodovia, a principal de acesso ao imóvel (ex: 'BR-282'). "
    "Se houver várias no documento, escolha a mais relevante. "
    "Se não constar, use seu conhecimento geográfico para informar a rodovia federal ou estadual mais próxima — NUNCA retorne null\n"
    "- proprietarios: array de strings em Title Case, cada item com nome + CPF ou CNPJ se presente (ex: ['João da Silva - CPF 000.000.000-00'])\n"
    "- endereco: SOMENTE o logradouro, no formato 'Rua Nome', 'Estrada Nome' ou 'Rodovia Nome/Sigla' — sem número, sem complemento\n"
    "- numero: número do imóvel exato ou 'S/N' se não houver\n"
    "- bairro: nome do bairro ou null\n"
    "- complemento: APENAS uma das categorias a seguir se aplicável — 'Fazenda Nome', 'Linha Nome', 'Lote N', 'Loteamento Nome', 'Quadra N', 'Condomínio Nome' ou 'Edifício Nome'; null se nenhuma se aplicar\n"
    "- unidade: identificação exata da unidade autônoma como consta no documento, se houver (ex: 'Casa nº 01', 'Apartamento nº 302', 'Sala 05'). Retorne null se não houver unidade específica (terreno simples)\n"
    "- pavimento: número do pavimento da unidade autônoma como consta no documento (ex: '3', '10'). Retorne null se não houver\n"
    "- areas_privativas: se o documento descrever áreas da unidade autônoma (área privativa, área de uso comum, fração ideal, área total, etc.), retorne array de objetos com {tipo: string exato como consta no documento, valor: string numérica com vírgula decimal}. Retorne null se não houver\n"
    "- tipo_imovel: 'RURAL' ou 'URBANO'\n"
    "- area_total: área total do imóvel. Se RURAL, SEMPRE converta para hectares (ha) independente da unidade original "
    "(ex: 10.512 m² → '1,0512 ha', 43.560 m² → '4,3560 ha'). Se URBANO, retorne em m² (ex: '600,00 m²')\n"
    "- cidade: nome do município\n"
    "- uf: sigla do estado (ex: 'SC')\n"
    "- averbacoes: liste SOMENTE construções, edificações ou demolições com AV. explícita no documento\n"
    "- averbacoes_classificadas: CRÍTICO — leia TODAS as averbações do documento e classifique por tipo. Retorne objeto com estas chaves exatas: construcoes_demoliciones, areas_nao_edificaveis, ferrovias_gasodutos, desmembramentos, remembramentos, reservas_legais (cada uma lista de strings, [] se não houver). Copie o texto de cada averbação EXATAMENTE como consta no documento, incluindo número da AV. e data\n"
    "- analise_juridica: CRÍTICO — analise TODAS as averbações, registros, ônus e restrições do documento. "
    "Para cada ocorrência encontrada, retorne um objeto com: id_av, tipo (categoria: 'Ônus e Gravames', 'Ações Judiciais e Litígios', "
    "'Restrições Administrativas/Urbanísticas/Ambientais', 'Riscos Dominiais e Registrais', 'Direitos de Terceiros/Ocupação'), "
    "subtipo, descricao, credora (ou null), cancelada (true/false), impacto ('Baixo'/'Médio'/'Alto'). "
    "NÃO inclua averbações de construção/demolição/desmembramento/remembramento nem já canceladas. Se não houver, retorne lista vazia []\n"
    "- confrontacoes: objeto {frente: string, fundos: string, direita: string, esquerda: string} com a descrição EXATA "
    "de cada confrontação como consta no documento (nome de rua, ou nome do confrontante/vizinho, ou 'não consta'). "
    "Use os termos 'frente', 'fundos', 'direita' e 'esquerda' relativos a quem olha o imóvel da rua\n"
    "- azimutes: procure no documento descrição de perímetro com azimutes e distâncias (texto corrido tipo 'ponto P1... azimute de 175°08'34\"... percorre 234,57m... até o ponto P2'). "
    "Extraia TODOS os trechos em ordem: {ponto_origem: 'P1', azimute: '175d08m34s', distancia_m: 234.57}. O primeiro ponto DEVE ter coordenadas UTM (E e N) — extraia no campo coordenadas também. Se não houver, retorne null\n"
    "- coordenadas: CRÍTICO — procure coordenadas em TODO o documento, incluindo tabelas SIGEF/INCRA que podem se estender por VÁRIAS PÁGINAS, sem exceção. "
    "Formatos possíveis: (1) DECIMAL simples → formato:'DECIMAL', pontos:[{x:longitude,y:latitude}]; "
    "(2) GMS em tabela SIGEF/INCRA (Longitude/Latitude em graus/minutos/segundos, hemisfério negativo=W/S) → formato:'GMS', pontos:[{lat_g,lat_m,lat_s,lat_hem,lon_g,lon_m,lon_s,lon_hem}]; "
    "(3) UTM com zona → formato:'UTM', pontos:[{x,y}]; "
    "(4) UTM sem zona explícita (documento com azimutes) → formato:'UTM', zona_utm:22, hemisferio:'S', pontos:[{x,y}]. "
    "Se não houver coordenadas, retorne null. Objeto: {formato:'UTM'/'GMS'/'DECIMAL', zona_utm:int ou null, hemisferio:'S'/'N' ou null, pontos:[...]}\n"
    "- vaga_garagem: true se houver qualquer menção a vaga de garagem, box ou garagem no documento; false se não houver\n"
    "- matricula_cancelada: CRÍTICO — verifique se a PRÓPRIA matrícula consta como cancelada, encerrada, extinta ou "
    "transferida para outra matrícula (ex: 'matrícula cancelada', 'encerrada por unificação', 'transferida para a matrícula nº X'). "
    "Retorne {cancelada: true/false, motivo: string exata do trecho ou null}. Se não houver indicação, retorne {cancelada: false, motivo: null}\n"
    "- croqui_svg: Gere um croqui SVG desta matrícula, analisando rigorosamente as posições e o ponto de observação "
    "descritos para posicionar corretamente as divisas e confrontantes. Retorne o código SVG completo como string "
    "(começando com '<svg' e terminando com '</svg>'), com os lados identificados (frente/fundos/laterais) e os "
    "nomes dos confrontantes de cada lado. É um esquema ilustrativo baseado na descrição textual, não uma medição "
    "precisa. Retorne null se não houver confrontações/posições suficientes no documento\n\n"
    "Depois de analisar TODAS as matrículas, preencha 'analise_confrontantes' comparando as confrontações de cada uma entre si: "
    "'sao_confrontantes' deve ser true SOMENTE se houver correspondência clara entre a confrontação de uma matrícula "
    "e a descrição de vizinhança/confrontante de outra, indicando que compartilham divisa e poderiam formar um único terreno contíguo. "
    "'explicacao' deve justificar em texto claro e direto, citando qual lado de qual matrícula confronta com qual lado de qual outra. "
    "Se houver apenas 1 matrícula, retorne sao_confrontantes:false e explicacao:'Apenas uma matrícula informada — não há o que comparar.'\n\n"
    "Retorne SOMENTE o JSON, sem explicações, sem markdown."
)

PROMPT_ANTIGO = (
    "Analise este laudo de avaliação imobiliária e retorne APENAS um JSON válido sem texto extra, sem markdown. "
    "Campos obrigatórios:\n"
    "- matricula: número(s) da(s) matrícula(s) EXATAMENTE como constam no documento. Se houver mais de uma (ex: '118.649 e 118.582'), retorne todas como string\n"
    "- cri: nome do cartório em Title Case, sem nome do oficial\n"
    "- coordenadas_raw: coordenadas exatas como aparecem no documento ou null\n"
    "- testada: medida do lado do imóvel que faz confrontação com a RUA ou LOGRADOURO PÚBLICO (frente do imóvel). "
    "Identifique nas confrontações qual lado confronta com rua, avenida, travessa, alameda ou logradouro e use APENAS essa medida. "
    "Formato: número exato + ' metros' (ex: '7,00 metros'). Se não houver confrontação com rua, retorne null\n"
    "- profundidade: medida do lado perpendicular à testada (lado do imóvel), número exato + ' metros' ou null\n"
    "- incra: se RURAL, código INCRA exato (ex: '950.114.354.341-4'); se URBANO, inscrição imobiliária municipal exata "
    "(ex: '03.01.00005.00003.1'). Procure por 'Inscrição Imobiliária', 'Insc. Imob.', 'Cadastro Municipal', 'Cód. INCRA', 'INCRA' ou similar. Retorne null se não encontrado\n"
    "- car: código CAR ou null\n"
    "- cidades_vizinhas: array com os 2 municípios mais populosos que fazem divisa direta com o município do imóvel — use seu conhecimento geográfico do Brasil para determinar\n"
    "- rodovias_acesso: OBRIGATÓRIO — retorne APENAS UMA rodovia, a principal de acesso ao imóvel (ex: 'BR-282'). "
    "Se houver várias no documento, escolha a mais relevante. "
    "Se não constar, use seu conhecimento geográfico para informar a rodovia federal ou estadual mais próxima — NUNCA retorne null\n"
    "- fonte_croqui: fonte do croqui como consta no documento\n"
    "- proprietarios: array de strings em Title Case com CPF/CNPJ se presentes\n"
    "- cep: CEP do imóvel\n"
    "- endereco: SOMENTE o(s) logradouro(s) exatamente como constam no documento, podendo ser dois separados por ' / ' "
    "(ex: 'Rua Alceu Simões Machado / Rua Ataulpa Guterres') — sem número, sem bairro, sem complemento\n"
    "- numero: número do imóvel ou 'S/N'\n"
    "- bairro: nome do bairro em Title Case ou null\n"
    "- complemento: quadra/setor/lote/loteamento/condomínio exatamente como consta no documento em Title Case "
    "(ex: 'Quarteirão 12 / Setor 03', 'Lote 5', 'Quadra 3') ou null se não houver\n"
    "- uf: sigla do estado\n"
    "- cidade: nome do município\n"
    "- tipo_imovel: 'RURAL' ou 'URBANO'\n"
    "- area_total: área total do imóvel. Se RURAL, SEMPRE converta para hectares (ha) independente da unidade original "
    "(ex: 10.512 m² → '1,0512 ha', 43.560 m² → '4,3560 ha'). Se URBANO, retorne em m² (ex: '600,00 m²')\n"
    "- averbacoes: liste SOMENTE construções, edificações ou demolições com AV. explícita\n"
    "- averbacoes_classificadas: CRÍTICO — classifique TODAS as averbações por tipo: construcoes_demoliciones, areas_nao_edificaveis, ferrovias_gasodutos, desmembramentos, remembramentos, reservas_legais. Copie o texto exato de cada averbação. Se não houver, retorne lista vazia []\n"
    "se nenhuma, retorne 'Não há averbações de construção ou demolição'\n"
    "- analise_juridica: CRÍTICO — analise TODAS as averbações, registros, ônus e restrições do documento. "
"Para cada ocorrência encontrada, retorne um objeto com: "
"id_av (número/identificador da averbação exatamente como consta no documento, ex: 'AV. 3', 'AV. 13.123', 'R.3'; se não houver identificador, use 'Averbação sem número identificado'), "
"tipo (categoria: 'Ônus e Gravames', 'Ações Judiciais e Litígios', 'Restrições Administrativas/Urbanísticas/Ambientais', 'Riscos Dominiais e Registrais', 'Direitos de Terceiros/Ocupação'), "
"subtipo (ex: 'Alienação fiduciária', 'Hipoteca', 'Penhora', 'APP', 'Embargo', 'Usufruto', 'Servidão', etc.), "
"descricao (descrição resumida do conteúdo), "
"credora (nome da instituição credora/beneficiária se houver, null se não houver), "
"cancelada (true se a averbação já foi expressamente cancelada/baixada no documento, false se vigente ou indefinido), "
"impacto ('Baixo', 'Médio' ou 'Alto'). "
"IMPORTANTE: inclua APENAS ocorrências que representem risco jurídico, restrição, ônus, limitação ao domínio, "
"redução de liquidez ou potencial impacto negativo na negociação. NÃO inclua averbações de construção, "
"demolição, desmembramento ou remembramento (essas já estão em averbacoes_classificadas). "
"NÃO inclua averbações já canceladas. "
"Se não houver nenhuma ocorrência relevante, retorne lista vazia [].\n"
    "- parecer: extraia EXATAMENTE os parágrafos do parecer/laudo descritivo do imóvel como constam no documento. "
    "O parecer normalmente possui 4 parágrafos: (1) descrição do terreno com área, localização, testada, profundidade e características físicas; "
    "(2) tipo de via e pavimentação; (3) infraestrutura da região; (4) uso da via, padrão construtivo, distância até rodovia e centro. "
    "Copie o texto EXATO de cada parágrafo separados por '\\n\\n'. NÃO inclua tabelas, títulos de seção nem descrições de edificações.\n"
    "- azimutes: CRÍTICO — procure no documento descrição de perímetro com azimutes e distâncias. Esse formato aparece como texto corrido, ex: 'A poligonal tem início no ponto P1, de coordenadas E:378961.094 e N:7015397.121, segue com o azimute de 175°08\'34\" e percorre 234,57m, até o ponto P2'. Extraia TODOS os trechos em ordem, do P1 até fechar o polígono. Para cada trecho retorne: {ponto_origem: 'P1', azimute: '175d08m34s', distancia_m: 234.57}. IMPORTANTE: converta o azimute para o formato grausXminutosYsegundosZ, ex: 175°08\'34\" → '175d08m34s'. O primeiro ponto DEVE ter coordenadas UTM (E e N) — extraia essas coordenadas também no campo coordenadas. Se não houver descrição por azimutes no documento, retorne null\n"
    "- coordenadas: CRÍTICO — procure coordenadas em TODO o documento, incluindo tabelas SIGEF/INCRA que podem se estender por VÁRIAS PÁGINAS. "
    "Formatos possíveis:\n"
    "(1) DECIMAL simples: '-29.184530, -51.180262' → formato:'DECIMAL', pontos:[{x:longitude,y:latitude}]\n"
    "(2) GMS em tabela SIGEF/INCRA: a tabela tem colunas Código, Longitude, Latitude, Altitude, etc. "
    "Longitude no formato '-51°14'02,673\"' e Latitude no formato '-28°02'24,036\"' ou com vírgula como decimal. "
    "ATENÇÃO: a tabela pode ter 100+ linhas espalhadas por múltiplas páginas — leia TODAS as páginas e extraia ABSOLUTAMENTE TODOS os vértices sem exceção. "
    "Não pare de ler antes de chegar ao fim da tabela. Cada linha é um vértice e todos são necessários para fechar o polígono corretamente. "
    "Hemisfério: longitude negativa = W (Oeste), latitude negativa = S (Sul). "
    "Use formato:'GMS', pontos:[{lat_g,lat_m,lat_s,lat_hem,lon_g,lon_m,lon_s,lon_hem}]\n"
    "(3) UTM com zona → formato:'UTM', pontos:[{x,y}]\n"
    "(4) Coordenadas UTM sem zona explícita — ex: E:378961.094 e N:7015397.121 em documento com azimutes: use formato:'UTM', zona_utm:22, hemisferio:'S', pontos:[{x:378961.094,y:7015397.121}]\n"
    "Se não houver coordenadas, retorne null. "
    "Objeto: {formato:'UTM'/'GMS'/'DECIMAL', zona_utm:int ou null, hemisferio:'S'/'N' ou null, "
    "pontos: UTM:[{x,y}] / GMS:[{lat_g,lat_m,lat_s,lat_hem,lon_g,lon_m,lon_s,lon_hem}] / DECIMAL:[{x:lon,y:lat}]}\n"
    "- grupos_vistoria: identifique TODOS os tipos de bem/item avaliado no laudo. "
    "Para cada um crie um objeto com: nome (ex: 'Terreno Urbano', 'Área Útil', 'Área Mecanizável', 'Casa'), "
    "construcao:'S' se tiver edificação, senão 'N', "
    "averbado:'S' se tiver AV. na matrícula, senão 'N', "
    "area: string numérica SEM pontos de milhar COM vírgula decimal, MANTENDO a unidade original do laudo: "
    "se o laudo informa em ha use ha (ex: '43,5600'), se em m² use m² (ex: '11324,26'). "
    "unidade_area: 'ha' ou 'm²' conforme o laudo. "
    "valor_unidade: valor unitário por unidade de área se informado, senão null, "
    "obs: descrição da edificação exatamente como consta no documento (ex: 'Em madeira. O acabamento das paredes internas é em madeira...'), ou null se não houver descrição, tem_foto: true. "
    "IMPORTANTE: SEMPRE retorne ao menos 1 grupo com o item principal avaliado e sua área total. "
    "Para imóvel rural com Área Útil 2,0000 ha e Área Mecanizável 41,5600 ha, retorne ambos os grupos. "
    "Ex rural: [{nome:'Área Útil',construcao:'N',averbado:'N',area:'2,0000',unidade_area:'ha',valor_unidade:null,obs:null,tem_foto:true},"
    "{nome:'Área Mecanizável',construcao:'N',averbado:'N',area:'41,5600',unidade_area:'ha',valor_unidade:null,obs:null,tem_foto:true}]\n"
    "Retorne SOMENTE o JSON, sem explicações, sem markdown."
)

# ──────────────────────────────────────────────────────────────


PROMPT_AZIMUTES = (
    "Leia este documento e extraia as informações de azimutes e coordenadas do perímetro do imóvel. "
    "O documento descreve o perímetro em texto corrido como: "
    "'A poligonal tem início no ponto P1, de coordenadas E:378961.094 e N:7015397.121, "
    "segue com o azimute de 175°08\'34\" e percorre 234,57m, até o ponto P2, confrontando com... "
    "deste segue com o azimute de 267°13\'40\" e percorre 24,00m, até o ponto P3...'. "
    "Retorne APENAS um JSON válido sem markdown com: "
    "- ponto_inicial: objeto {x: valor_E_numerico, y: valor_N_numerico} com as coordenadas UTM do ponto P1 "
    "- zona_utm: número da zona UTM (se não constar, use 22) "
    "- azimutes: array com TODOS os trechos em ordem, cada um com "
    "{ponto_origem: 'P1', azimute: '175d08m34s', distancia_m: 234.57} "
    "onde o azimute DEVE estar no formato GRAUSdMINUTOSmSEGUNDOs (ex: 175°08\'34\" → '175d08m34s'). "
    "Extraia TODOS os trechos até o polígono fechar. "
    "Se não houver descrição por azimutes, retorne {ponto_inicial: null, azimutes: null}. "
    "Retorne SOMENTE o JSON, sem explicações, sem markdown."
)
